### ISSUE TITLE
行程码newtime的时间提早了八个小时

### ISSUE THREAD

**Issue by BronyaInUSTC** [cyzkrau/AutoDailyReport-For-USTC#1]
这是否是因为代码运行的环境中设置的时区不正确

**Comment by cyzkrau** [comment]
这里是按照系统时间上传的，如果在github服务器上运行会按照GMT+0，会比北京时间提前8小时

**Comment by NightGlow0826** [comment]
喔谢谢，那我直接把newtime里面的localtime()加上八个小时

**Comment by cyzkrau** [comment]
可以，但可能需要检查是否会出现时间的问题

**Comment by cyzkrau** [comment]
代码完善了这个问题(虽然我觉得差几个小时问题不大)
