### ISSUE TITLE
打卡平台有小更新，另外，自动跨校区报备功能不可用

### ISSUE THREAD

**Issue by Mhhhaster** [cyzkrau/AutoDailyReport-For-USTC#2]

**Comment by cyzkrau** [comment]
我这边本地运行暂时没有遇到问题，你可以检查一下是不是核酸报告或者安康码没有同步好

**Comment by Mhhhaster** [comment]
> 我这边本地运行暂时没有遇到问题，你可以检查一下是不是核酸报告或者安康码没有同步好

噢噢，不好意思，主校区那边是可以的，就高新不给进

**Comment by inklife** [comment]
自动跨校区报备功能失效，是不是学校又改了字段
```
Run python runme.py "$STUID" "$PASSWORD"
Login Successful!
daily report successful!
update successful
Traceback (most recent call last):
  File "runme.py", line 49, in <module>
    & autorepoter.cross_campus(cross_campus_data)
  File "/home/runner/work/AutoDailyReport-For-THU/AutoDailyReport-For-THU/Report.py", line 59, in cross_campus
    start_date = soup.find("input", {"id": "start_date"})["value"]
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code [1](https://github.com/inklife/AutoDailyReport-For-THU/runs/7380691915?check_suite_focus=true#step:5:1).
```

**Comment by cyzkrau** [comment]
> 

我这边目前没有在校状态的账号，需要等假期结束之后修改

**Comment by cyzkrau** [comment]
> 自动跨校区报备功能失效，是不是学校又改了字段
> 
> ```
> Run python runme.py "$STUID" "$PASSWORD"
> Login Successful!
> daily report successful!
> update successful
> Traceback (most recent call last):
>   File "runme.py", line 49, in <module>
>     & autorepoter.cross_campus(cross_campus_data)
>   File "/home/runner/work/AutoDailyReport-For-THU/AutoDailyReport-For-THU/Report.py", line 59, in cross_campus
>     start_date = soup.find("input", {"id": "start_date"})["value"]
> TypeError: 'NoneType' object is not subscriptable
> Error: Process completed with exit code [1](https://github.com/inklife/AutoDailyReport-For-THU/runs/7380691915?check_suite_focus=true#step:5:1).
> ```

我这边目前没有在校状态的账号，需要等假期结束之后修改
